// Shape of mcp/data/scripts-index.json, generated by mcp/scripts/generate-index.mjs
// from the comment-based help blocks of every script under scripts/.

export interface ScriptParameter {
  name: string;
  type: string;
  mandatory: boolean;
  default?: string;
  switch: boolean;
}

export interface RunbookInfo {
  eligible: boolean;
  runtime: string;
  exclusionReason: string;
}

export interface AzureDeploy {
  deployUrl: string;
  templateUrl: string;
  supportsExistingAutomationAccount: boolean;
}

export interface ScriptMeta {
  id: string;
  title: string;
  synopsis: string;
  description: string;
  category: string;
  categoryLabel: string;
  tags: string[];
  permissions: string[];
  minRole: string;
  platform: string;
  author: string;
  version: string;
  lastUpdate: string;
  schedule: string;
  execution: string;
  output: string;
  remediationType: string;
  pairScript: string;
  parameters: ScriptParameter[];
  examples: string[];
  notes: string;
  path: string;
  rawUrl: string;
  githubUrl: string;
  // Present in indexes generated after the runbook/deploy metadata was added;
  // treat as absent when reading an older committed index.
  runbook?: RunbookInfo;
  azureDeploy?: AzureDeploy | null;
}

export interface ScriptIndex {
  repository: string;
  branch: string;
  generated: string;
  count: number;
  categories: string[];
  scripts: ScriptMeta[];
}

/** Where catalog data was served from, surfaced in tool output for debuggability. */
export type CatalogSource = "github" | "github (stale cache)" | "bundled";

/**
 * Data-access contract for the MCP server. The production repository fetches
 * from GitHub raw with caching and fallbacks; tests supply an in-memory fixture.
 */
export interface ScriptRepository {
  getIndex(): Promise<{ index: ScriptIndex; source: CatalogSource }>;
  getInstructions(): Promise<{ text: string; source: CatalogSource }>;
  getScriptSource(script: ScriptMeta): Promise<string>;
}
