import type { Metadata } from "next";
import Navbar from "~/components/navbar";
import Footer from "~/components/footer";
import { ScriptsProvider } from "~/components/scripts-provider";

export const metadata: Metadata = {
  title: "Terms of Use",
  description:
    "Terms of Use for IntuneAutomation.com and the AI Script Generator.",
  alternates: { canonical: "/terms" },
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <ScriptsProvider>
      <div className="bg-background text-foreground min-h-screen">
        <Navbar />
        <div className="container mx-auto max-w-3xl px-4 py-10 sm:py-16">
          <h1 className="mb-2 text-3xl font-semibold tracking-tight">
            Terms of Use
          </h1>
          <p className="text-muted-foreground mb-10 text-sm">
            Effective: May 11, 2026
          </p>

          <div className="legal-prose text-[15px] leading-relaxed">
            <p>
              These Terms of Use govern access to and use of IntuneAutomation.com,
              including the AI Script Generator (collectively, the
              &quot;Service&quot;). By using the Service, you agree to these
              Terms.
            </p>

            <h2>Access and Eligibility</h2>
            <p>
              The Service is provided free of charge. You may use the Service
              without registration. By using the Script Generator you confirm
              that you are authorized to write PowerShell scripts for the
              Microsoft Intune, Microsoft Graph, or Windows / macOS device
              management environments you intend to use them in, and that your
              use complies with the policies of those environments and any
              applicable laws.
            </p>

            <h2>Use of the Service</h2>
            <p>
              The Script Generator takes a natural-language description and
              returns a PowerShell script using Anthropic&apos;s Claude
              language model. The Service does <em>not</em> connect to your
              Microsoft tenant, does not authenticate against Microsoft Graph
              on your behalf, and does not run any generated script. The
              output is delivered to your browser only; you choose whether to
              copy or download it.
            </p>
            <p>Prohibited activities include:</p>
            <ul>
              <li>
                Attempting to use the Service to generate malware, exploits,
                or any code intended to cause harm to systems you do not own
                or do not have authorization to test
              </li>
              <li>
                Using the Service to circumvent security controls or access
                systems without authorization
              </li>
              <li>
                Automated scraping, programmatic abuse of the generation
                endpoints, or attempts to bypass rate limits, Turnstile bot
                verification, or the daily spend cap
              </li>
              <li>
                Submitting prompts containing personal data of third parties
                without their consent, or submitting secrets, credentials,
                tenant identifiers, or other confidential information
              </li>
              <li>
                Reverse-engineering, redistributing, or repackaging the
                Service as your own offering
              </li>
            </ul>

            <h2>AI-Generated Content</h2>
            <p>
              All scripts produced by the Script Generator are generated by a
              large language model and may contain errors, hallucinated
              cmdlets or permissions, incorrect Graph API usage, security
              flaws, or other defects. You are solely responsible for:
            </p>
            <ul>
              <li>Reviewing the script in full before any use</li>
              <li>
                Testing the script in an isolated lab or non-production
                environment
              </li>
              <li>
                Verifying that all Microsoft Graph permissions, cmdlets, and
                endpoints referenced are accurate and currently supported by
                Microsoft
              </li>
              <li>Any consequences of running the script</li>
            </ul>
            <p>
              The Service includes an automated quality check that validates
              generated scripts against known Microsoft Graph permission
              scopes and common correctness patterns. This check is a helper,
              not a guarantee, and does not relieve you of the responsibility
              to review and test the output.
            </p>

            <h2>Disclaimer</h2>
            <p>
              The Service is provided on an &quot;as is&quot; and &quot;as
              available&quot; basis without warranties of any kind, express or
              implied, including but not limited to warranties of
              merchantability, fitness for a particular purpose, accuracy,
              non-infringement, or that the Service will be uninterrupted or
              error-free. The provider does not warrant the correctness or
              suitability of any generated script for any particular purpose.
            </p>

            <h2>Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, the provider
              assumes no responsibility for any indirect, incidental, special,
              consequential, or punitive damages, nor for any loss of data,
              profits, revenue, or goodwill arising out of or in connection
              with your use of the Service or any generated script.
            </p>

            <h2>Third-Party Processors</h2>
            <p>
              Prompts you submit are transmitted to Anthropic PBC (United
              States) for processing. See the{" "}
              <a href="/privacy/">Privacy Policy</a> for details on data flow,
              retention, and all third-party processors involved.
            </p>

            <h2>Intellectual Property</h2>
            <p>
              The website source code is open source under the license
              published in the project repository. Scripts generated by the
              Service are provided to you with no ownership claim by the
              provider; you may use, modify, and distribute them subject to
              these Terms and your obligation to verify them before use.
            </p>

            <h2>Changes</h2>
            <p>
              The provider may modify these Terms from time to time to reflect
              service improvements or legal requirements. Material changes
              will be reflected on this page with an updated effective date.
              Continued use of the Service after changes indicates acceptance
              of the updated Terms.
            </p>

            <h2>Contact</h2>
            <p>
              For inquiries about these Terms:{" "}
              <a href="mailto:support@ugurlabs.com">support@ugurlabs.com</a>
            </p>
          </div>
        </div>
        <Footer />
      </div>
    </ScriptsProvider>
  );
}
